#!/usr/bin/env python3
"""Build a wheel of void_agent whose core is native code.

`make compile` runs this. The checkout is never touched: the package is
copied into a staging directory (`build/compiled/`), every module under
`core/` and `providers/` is compiled by Cython into a native extension
(`.so` on macOS/Linux, `.pyd` on Windows), the `.py` of each compiled
module is left out of the wheel, a `.pyi` stub is generated in its place
so editors and type checkers keep working, and setuptools assembles the
result into `dist/`. The wheel is then audited: no source of a compiled
module may be inside it.

`--verify` goes one step further: a fresh venv, the wheel installed, the
framework's test suite run against it, with the checkout's `src/` nowhere
on the path.

A native wheel is specific to one OS, one CPU architecture and one Python
minor version. Build once per target (`--python 3.12`): a release needs one
build per OS, architecture and Python minor. Never publish an sdist of it: an sdist is the
source.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
import zipfile
from collections.abc import Iterable
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = "void_agent"
SOURCE = ROOT / "src" / PACKAGE

# `core/` is folded into the package root before compiling: one extension
# module instead of thirty-two, so the wheel carries no module map. The
# providers stay separate — each pulls in an optional SDK, and importing them
# eagerly would make the extras mandatory.
COMPILED = ("providers",)
MERGED = "core"
# Every subpackage that outlives the fold and imports from core: their
# `from void_agent.core… import` lines are rewritten to the root. `mcp/` is
# among them but not in COMPILED — it is a bridge to an SDK, not the runtime,
# and ships as ordinary Python that type checkers read directly.
SATELLITES = ("providers", "mcp", "skills")

# The provider adapters are public entry points of their own: users import
# them directly, so each keeps a stub naming only its adapter class.
PROVIDER_CLASSES = {"anthropic": "AnthropicLlm", "openai": "OpenAiLlm"}

NATIVE_SUFFIXES = (".so", ".pyd")

DISTRIBUTION_README = """\
# void_agent

A turn-based agent framework, distributed as a compiled wheel: `void_agent.core`
and `void_agent.providers` are native extension modules.

    import void_agent

The public API is re-exported at the package root and fully typed —
`__init__.pyi` ships beside it, so editors and type checkers work normally.
"""

BUILD_SYSTEM = """\
[build-system]
requires = ["setuptools>=77", "cython>=3.1,<4"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["void_agent", "void_agent.*"]

[tool.setuptools.package-data]
"*" = ["*.pyi", "py.typed"]
"""

SETUP_PY = '''\
"""Generated by scripts/compile.py — do not edit; its docstring explains."""

import sys
from pathlib import Path

from Cython.Build import cythonize
from Cython.Compiler import Options
from setuptools import setup
from setuptools.command.build_py import build_py as _build_py

PACKAGE = @PACKAGE@
COMPILED = @COMPILED@
JOBS = @JOBS@

# Python semantics, not C semantics. Annotations stay annotations
# (`annotation_typing=False`: `x: int` must not become a C long); functions
# stay introspectable (`binding=True`: `inspect.signature`, `__annotations__`
# and `__doc__` all work, and the tool mechanism relies on every one of
# them); keyword arguments are always accepted. Docstrings are kept because
# `tool()` reads a handler's docstring as its description.
DIRECTIVES = {
    "language_level": "3",
    "annotation_typing": False,
    "binding": True,
    "always_allow_keywords": True,
    "emit_code_comments": False,
}

# Our docstrings would otherwise sit in the binary in full. Nothing here needs
# them at runtime: the built-in tools pass explicit descriptions, and `tool()`
# reads `inspect.getdoc` only from a caller's own handler, which this script
# never compiles. Not a compiler directive — a global on the compiler.
Options.docstrings = False

sources = sorted(
    [Path(PACKAGE, "__init__.py").as_posix()]
    + [path.as_posix() for sub in COMPILED for path in Path(PACKAGE, sub).rglob("*.py")]
)
extensions = cythonize(
    sources, build_dir="build/cython", quiet=True, compiler_directives=DIRECTIVES
)

# No debug info, no local symbols: nothing in the binary but what it needs.
if sys.platform == "win32":
    compile_args, link_args = [], []
elif sys.platform == "darwin":
    compile_args, link_args = ["-g0"], ["-Wl,-x"]
else:
    compile_args, link_args = ["-g0"], ["-Wl,-s"]
for ext in extensions:
    ext.extra_compile_args = compile_args
    ext.extra_link_args = link_args

COMPILED_MODULES = {ext.name for ext in extensions}


class build_py(_build_py):
    """Leave the `.py` of every compiled module out of the wheel: the
    extension *is* the module. Everything else — the package root, the
    stubs, `py.typed` — ships as usual."""

    def find_package_modules(self, package, package_dir):
        modules = super().find_package_modules(package, package_dir)
        return [m for m in modules if f"{m[0]}.{m[1]}" not in COMPILED_MODULES]


setup(
    ext_modules=extensions,
    cmdclass={"build_py": build_py},
    options={"build_ext": {"parallel": JOBS}},
)
'''


def run(*cmd: str, cwd: Path = ROOT, env: dict[str, str] | None = None) -> None:
    print("$", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, env=env, check=True)


# --- the staging tree ---------------------------------------------------------


def toml_key(key: str) -> str:
    return key if re.fullmatch(r"[A-Za-z0-9_-]+", key) else json.dumps(key)


def toml_value(value: object) -> str:
    """One TOML value — enough for a `[project]` table: strings, numbers,
    lists, inline tables (authors)."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)  # JSON escapes are valid TOML basic-string escapes
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in cast(list[object], value)) + "]"
    if isinstance(value, dict):
        items = cast(dict[str, object], value).items()
        return "{ " + ", ".join(f"{toml_key(k)} = {toml_value(v)}" for k, v in items) + " }"
    raise TypeError(f"cannot serialise {type(value).__name__} to TOML")


def toml_table(name: str, table: dict[str, object]) -> str:
    """`[name]` with its scalar keys, then one `[name.sub]` per nested table
    (`urls`, `optional-dependencies`)."""
    lines = [f"[{name}]"]
    subtables: list[tuple[str, dict[str, object]]] = []
    for key, value in table.items():
        if isinstance(value, dict):
            subtables.append((f"{name}.{key}", cast(dict[str, object], value)))
        else:
            lines.append(f"{toml_key(key)} = {toml_value(value)}")
    text = "\n".join(lines) + "\n"
    for sub_name, sub in subtables:
        text += "\n" + toml_table(sub_name, sub)
    return text


def stage_tree(stage: Path, jobs: int) -> None:
    """A copy of the package plus a setuptools project around it. The
    metadata is the checkout's own `[project]` table, verbatim, so the
    compiled wheel and the pure one describe the same distribution."""
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    shutil.copytree(
        SOURCE, stage / PACKAGE, ignore=shutil.ignore_patterns("__pycache__", "*.py[co]")
    )
    pyproject = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = cast(dict[str, object], pyproject["project"])
    if (ROOT / "LICENSE").exists():
        shutil.copy(ROOT / "LICENSE", stage / "LICENSE")
    # The project README describes the source layout, so it must not become
    # this wheel's long description — the metadata of a compiled distribution
    # would otherwise carry a tour of the package's internals.
    (stage / "README.md").write_text(DISTRIBUTION_README, encoding="utf-8")
    (stage / "pyproject.toml").write_text(
        toml_table("project", project) + "\n" + BUILD_SYSTEM, encoding="utf-8"
    )
    setup_py = (
        SETUP_PY.replace("@PACKAGE@", repr(PACKAGE))
        .replace("@COMPILED@", repr(COMPILED))
        .replace("@JOBS@", repr(jobs))
    )
    (stage / "setup.py").write_text(setup_py, encoding="utf-8")


def _stubgen(into: Path, docstrings: bool) -> Path:
    """Draft stubs for every module, into a scratch directory that is never
    packaged. Private names (`_x`) are left out by stubgen itself."""
    flags = ["--include-docstrings"] if docstrings else []
    run(
        "uvx",
        "--from",
        "mypy>=1.10",
        "stubgen",
        "--no-import",
        *flags,
        "--quiet",
        "-o",
        str(into),
        str(SOURCE / MERGED),
        *(str(SOURCE / sub) for sub in COMPILED),
    )
    return into / PACKAGE


def _flatten(files: Iterable[Path]) -> tuple[set[str], list[str]]:
    """One text from many stubs. Imports of our own modules go: the point is
    that nothing outside the public surface is named anywhere."""
    external: set[str] = set()
    bodies: list[str] = []
    for path in files:
        for line in path.read_text(encoding="utf-8").splitlines():
            if re.match(r"^(from|import) ", line):
                if PACKAGE not in line:
                    external.add(line)
            else:
                bodies.append(line)
    return external, bodies


def _definitions(tree: ast.Module) -> dict[str, ast.stmt]:
    found: dict[str, ast.stmt] = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            found[node.name] = node
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            found[node.target.id] = node
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    found[target.id] = node
    return found


def _prune(text: str, seeds: set[str]) -> str:
    """Keep the seeds and whatever their signatures reach; drop the rest.

    Everything a caller can name stays; the machinery behind it — the loop's
    states, tool registrations, the dispatch helpers, and the model-facing prompt
    constants — never appears in a file anyone can open."""
    tree = ast.parse(text)
    defined = _definitions(tree)

    keep: set[str] = set()
    queue = [seed for seed in seeds if seed in defined]
    while queue:
        name = queue.pop()
        if name in keep:
            continue
        keep.add(name)
        for node in ast.walk(defined[name]):
            if isinstance(node, ast.Name) and node.id in defined and node.id not in keep:
                queue.append(node.id)

    lines = text.splitlines()
    out: list[str] = []
    for node in tree.body:
        name = next((n for n, d in defined.items() if d is node and n in keep), None)
        if name is None:
            continue
        # `node.lineno` starts at `class`/`def`, skipping decorators — and
        # losing `@dataclass` loses `__match_args__`, which breaks every
        # `case Answer(value)` downstream.
        decorators = getattr(node, "decorator_list", [])
        start = min([node.lineno, *(d.lineno for d in decorators)])
        out.extend(lines[start - 1 : node.end_lineno])
        out.append("")
    return "\n".join(out)


def public_api() -> set[str]:
    """The names `void_agent/__init__.py` exports. That list is the contract;
    everything else is implementation."""
    init = (SOURCE / "__init__.py").read_text(encoding="utf-8")
    return set(re.findall(r'^\s+"(\w+)",', init.split("__all__")[1], re.M))


# --- folding core into one module -------------------------------------------


def _module_name(path: Path) -> str:
    parts = list(path.relative_to(SOURCE.parent).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def _merged_modules() -> dict[str, Path]:
    """Every module that folds into the root, keyed by its import name."""
    return {_module_name(p): p for p in sorted((SOURCE / MERGED).rglob("*.py"))}


def _import_order(modules: dict[str, Path]) -> list[str]:
    """Depth-first over the intra-package imports.

    A definition has to exist before the module-level code that uses it runs:
    a pydantic model resolving its annotations, a decorator, a default. The
    dependency graph is acyclic by design (see CLAUDE.md), so this is a plain
    topological sort, and a cycle is a bug worth failing the build on."""
    known = set(modules)
    edges: dict[str, set[str]] = {}
    for name, path in modules.items():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        edges[name] = {
            node.module
            for node in ast.walk(tree)
            if isinstance(node, ast.ImportFrom) and node.module in known
        }
    order: list[str] = []
    done: set[str] = set()
    visiting: set[str] = set()

    def visit(name: str) -> None:
        if name in done:
            return
        if name in visiting:
            raise RuntimeError(f"import cycle through {name}")
        visiting.add(name)
        for dependency in sorted(edges[name]):
            visit(dependency)
        visiting.discard(name)
        done.add(name)
        order.append(name)

    for name in sorted(modules):
        visit(name)
    return order


def _module_body(path: Path) -> tuple[set[str], list[str]]:
    """One module's code, with its imports lifted out.

    Imports of our own modules go: after the fold every name is a sibling.
    Docstrings and per-module `__all__` go too — the folded module states the
    public surface once, at the end."""
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    lines = source.splitlines()
    external: set[str] = set()
    body: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        if isinstance(node, ast.ImportFrom) and (node.module or "").startswith(PACKAGE):
            continue
        if isinstance(node, ast.Import | ast.ImportFrom):
            external.update(lines[node.lineno - 1 : node.end_lineno])
            continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            continue  # the module docstring
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets
        ):
            continue
        decorators = getattr(node, "decorator_list", [])
        start = min([node.lineno, *(d.lineno for d in decorators)])
        body.extend(lines[start - 1 : node.end_lineno])
    return external, body


DIR_HOOK = '''

def __dir__() -> list[str]:
    """Completion and `dir()` see the public API and nothing else."""
    return sorted([*__all__, "__version__"])
'''


def fold_core(stage: Path) -> None:
    """Rewrite the staged package so `core/` is gone and its code lives in
    `__init__.py`, with the providers importing from the root instead.

    Nothing about the public API changes: the same names are defined, in the
    same order of effect. What changes is that the wheel stops naming a single
    internal module."""
    modules = _merged_modules()
    externals: set[str] = set()
    body: list[str] = []
    for name in _import_order(modules):
        module_externals, module_body = _module_body(modules[name])
        externals |= module_externals
        body.extend([*module_body, ""])

    root = (SOURCE / "__init__.py").read_text(encoding="utf-8")
    version = root[root.index("try:") : root.index("__all__")]
    exported = root[root.index("__all__") :]

    folded = "\n".join(
        [
            "from __future__ import annotations",
            "",
            "import importlib.metadata",
            *sorted(externals),
            "",
            "",
            *body,
            version.rstrip(),
            "",
            exported.rstrip(),
            DIR_HOOK,
        ]
    )
    (stage / PACKAGE / "__init__.py").write_text(folded, encoding="utf-8")
    shutil.rmtree(stage / PACKAGE / MERGED)

    pattern = re.compile(rf"from {PACKAGE}\.{MERGED}[\w.]* import")
    for satellite in SATELLITES:
        for path in sorted((stage / PACKAGE / satellite).rglob("*.py")):
            text = path.read_text(encoding="utf-8")
            path.write_text(pattern.sub(f"from {PACKAGE} import", text), encoding="utf-8")


def write_stubs(stage: Path, docstrings: bool = True) -> None:
    """One stub for the whole public surface, and one per provider.

    Type checkers prefer `__init__.pyi` over `__init__.py`, so a stub that
    declares the public API in full means they never look inside `core/` —
    and `core/` therefore ships no `.pyi` at all. Downstream typing is
    unaffected; the module layout, the internal classes and the prompt text
    stop being readable."""
    drafts = _stubgen(stage / "_stubs", docstrings)
    provider_dir = Path(PACKAGE) / "providers"

    core = sorted(p for p in drafts.rglob("*.pyi") if not set(p.parts) & set(SATELLITES))
    external, bodies = _flatten(core)
    body = _prune("\n".join(bodies), public_api())
    exported = "\n".join(f'    "{name}",' for name in sorted(public_api()))
    header = "\n".join(sorted(external))
    (stage / PACKAGE / "__init__.pyi").write_text(
        f"{header}\n\n{body}\n__all__ = [\n{exported}\n]\n", encoding="utf-8"
    )

    for module, exported_class in PROVIDER_CLASSES.items():
        external, bodies = _flatten([drafts / "providers" / f"{module}.pyi"])
        body = _prune("\n".join(bodies), {exported_class})
        target = stage / provider_dir / f"{module}.pyi"
        target.write_text("\n".join(sorted(external)) + "\n\n" + body, encoding="utf-8")
    shutil.rmtree(drafts.parent)


# --- the wheel ----------------------------------------------------------------


def build_wheel(stage: Path, out: Path, python: str | None) -> Path:
    staged_dist = stage / "dist"
    cmd = ["uv", "build", "--wheel", "--out-dir", str(staged_dist)]
    if python:
        cmd += ["--python", python]
    run(*cmd, str(stage))
    (wheel,) = staged_dist.glob("*.whl")
    out.mkdir(parents=True, exist_ok=True)
    target = out / wheel.name
    shutil.move(str(wheel), target)
    return target


def compiled_module_stems() -> list[str]:
    """`void_agent/core/agent`, … — every module that must be native."""
    return sorted(
        py.relative_to(SOURCE.parent).with_suffix("").as_posix()
        for py in [
            SOURCE / "__init__.py",
            *(f for sub in COMPILED for f in (SOURCE / sub).rglob("*.py")),
        ]
    )


def audit(wheel: Path) -> list[str]:
    """What must and must not be inside.

    Every compiled module is an extension and never source. Nothing under
    `core/` carries a stub: the public surface is declared once, at the root,
    so no internal name reaches a file anyone can read. And no internal name
    may appear in the stubs that do ship."""
    with zipfile.ZipFile(wheel) as zf:
        names = set(zf.namelist())
        stubs = [zf.read(n).decode("utf-8") for n in sorted(names) if n.endswith(".pyi")]
    problems: list[str] = []
    for stem in compiled_module_stems():
        if f"{stem}.py" in names:
            problems.append(f"source shipped: {stem}.py")
        if not any(n.startswith(f"{stem}.") and n.endswith(NATIVE_SUFFIXES) for n in names):
            problems.append(f"no extension for {stem}")
    problems.extend(
        f"the folded subpackage still ships: {n}"
        for n in sorted(names)
        if n.startswith(f"{PACKAGE}/{MERGED}/")
    )
    problems.extend(f"C source shipped: {n}" for n in sorted(names) if n.endswith(".c"))
    required = (
        f"{PACKAGE}/__init__.pyi",
        f"{PACKAGE}/py.typed",
        *(f"{PACKAGE}/providers/{module}.pyi" for module in PROVIDER_CLASSES),
    )
    problems.extend(f"missing {n}" for n in required if n not in names)
    named: set[str] = set()
    for stub in stubs:
        named |= _identifiers(stub)
    # The stub is what an editor completes from. A public name it does not
    # declare is a name the user cannot see, so treat it as a build failure —
    # this is the check that catches a stub that silently came out empty.
    root_stub = zipfile.ZipFile(wheel).read(f"{PACKAGE}/__init__.pyi").decode("utf-8")
    undeclared = sorted(public_api() - _identifiers(root_stub))
    problems.extend(f"public name missing from the stub: {name}" for name in undeclared)
    problems.extend(
        f"internal name in a shipped stub: {name}" for name in sorted(named & _internal_names())
    )
    return problems


def _identifiers(stub: str) -> set[str]:
    """Every name the stub's CODE refers to. Docstrings are prose — the word
    "attendant" in a sentence is not a reference to the function."""
    tree = ast.parse(stub)
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            found.add(node.id)
        elif isinstance(node, ast.Attribute):
            found.add(node.attr)
        elif isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            found.add(node.name)
        elif isinstance(node, ast.alias):
            found.add(node.asname or node.name)
    return found


def _internal_names() -> set[str]:
    """Top-level names the sources define that the public API does not export.

    Read from the sources rather than the stubs, so a name that stubgen
    starts emitting later is caught the first time it appears."""
    defined: set[str] = set()
    for sub in COMPILED:
        for path in (SOURCE / sub).rglob("*.py"):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            defined |= {
                node.name
                for node in tree.body
                if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef)
                and not node.name.startswith("_")
            }
    return defined - public_api() - set(PROVIDER_CLASSES.values())


# --- the proof ----------------------------------------------------------------


def verify(wheel: Path, stage: Path, python: str | None) -> None:
    """A fresh venv with the dev dependencies but not the project, the wheel
    installed into it, the whole suite run against it. The checkout's
    `src/` is not on the path: what the tests exercise is the binary."""
    venv = stage / "verify"
    env = {**os.environ, "UV_PROJECT_ENVIRONMENT": str(venv)}
    sync = ["uv", "sync", "--no-install-project"]
    if python:
        sync += ["--python", python]
    run(*sync, env=env)
    interpreter = venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    run("uv", "pip", "install", "--python", str(interpreter), str(wheel))
    probe = (
        f"import {PACKAGE} as m; "
        f"assert m.__file__.endswith({NATIVE_SUFFIXES!r}), m.__file__; "
        f"assert len(dir(m)) == len(m.__all__) + 1, dir(m); "
        f"print('native:', m.__file__)"
    )
    run(str(interpreter), "-c", probe)
    # Tests that import internals cannot pass against a folded wheel by
    # construction: those modules no longer exist. The CLI's tests exercise
    # the checkout's cli/, which the wheel does not carry, and lean on a
    # terminal's platform (ripgrep, clipboards, POSIX paths and modes) that a
    # Windows runner in the release matrix does not have. `make check` runs
    # both against the checkout; here the wheel answers for itself.
    run(
        str(interpreter),
        "-m",
        "pytest",
        "-q",
        "-p",
        "no:cacheprovider",
        "-m",
        "not internals",
        "--ignore-glob=tests/test_cli_*.py",
        "--ignore=tests/test_pack.py",
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--python",
        help="interpreter to build (and verify) with, e.g. 3.12; default: the project's",
    )
    parser.add_argument("--out", type=Path, default=ROOT / "dist", help="where the wheel goes")
    parser.add_argument(
        "--stage", type=Path, default=ROOT / "build" / "compiled", help="scratch tree, kept"
    )
    parser.add_argument(
        "--jobs", type=int, default=os.cpu_count() or 1, help="parallel C compiler jobs"
    )
    parser.add_argument(
        "--verify", action="store_true", help="install the wheel in a fresh venv, run the tests"
    )
    args = parser.parse_args()
    python = cast(str | None, args.python)
    stage = cast(Path, args.stage).resolve()
    out = cast(Path, args.out).resolve()

    stage_tree(stage, jobs=cast(int, args.jobs))
    fold_core(stage)
    write_stubs(stage)
    wheel = build_wheel(stage, out, python)

    problems = audit(wheel)
    if problems:
        print("wheel audit failed:", file=sys.stderr)
        for p in problems:
            print("  -", p, file=sys.stderr)
        return 1
    modules = compiled_module_stems()
    if cast(bool, args.verify):
        verify(wheel, stage, python)

    print()
    print(f"  wheel    {wheel.relative_to(ROOT) if wheel.is_relative_to(ROOT) else wheel}")
    print(
        f"  native   {len(modules)} modules under {', '.join(f'{PACKAGE}/{s}/' for s in COMPILED)}"
    )
    print(
        f"  stubs    {PACKAGE}/__init__.pyi declares the public API"
        f" ({len(public_api())} names); nothing under core/ is stubbed"
    )
    print(f"  size     {wheel.stat().st_size // 1024} KiB")
    if cast(bool, args.verify):
        print("  verified test suite green against the installed wheel (fresh venv)")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
